# PyTorch Basics

In [1]:
import torch

### Tensors

- A tensor is any number, vector (1-D Array), matrix (2-D Array) or any n-D Array.
- Tensors must have a **regular shape**.
- All the elements in a tensor are of **same data type**. If different data type elements are given type casting is done in upward direction.

In [2]:
t1 = torch.tensor(5.)

In [3]:
t1

tensor(5.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1., 2., 3., 4., 5.])

In [6]:
t3 = torch.tensor([[5., 6], [7, 6], [8, 9]])

In [7]:
t4 = torch.Tensor([[[11, 12, 13], [14, 15, 16]], [[17, 18, 19.], [20, 21, 22]]])

In [8]:
print(t2.dtype, t3.dtype, t4.dtype)

torch.float32 torch.float32 torch.float32


In [9]:
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3., 4., 5.])
tensor([[5., 6.],
        [7., 6.],
        [8., 9.]])
tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[17., 18., 19.],
         [20., 21., 22.]]])


In [10]:
print('Shape')
print('T1:', t1.shape, 'T2:', t2.shape, 'T3:', t3.shape, 'T4:', t4.shape)

Shape
T1: torch.Size([]) T2: torch.Size([5]) T3: torch.Size([3, 2]) T4: torch.Size([2, 2, 3])


### Tensor Operations

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [12]:
y = w * x + b

In [13]:
y

tensor(17., grad_fn=<AddBackward0>)

Once calculation is done. We can use `backward()` function to calculate devative of y w.r.t tensors that have `requires_grad` set to `True`

In [14]:
y.backward()

In [15]:
print('dy/dx:', x.grad, 'dy/dw:', w.grad, 'dy/db:', b.grad)

dy/dx: None dy/dw: tensor(3.) dy/db: tensor(1.)


### Interoperability with NumPy

In [16]:
import numpy as np

In [17]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [18]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Using the `from_numpy()` uses the same memory location as numpy array, whereas `tensor()` funtion create a copy within the memory

In [19]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [20]:
z = y.numpy()

In [21]:
z

array([[1., 2.],
       [3., 4.]])

The major difference in a Torch Tensor and NumPy Array is the Torch Tensor are designed specifically to run **optimized operations on GPUs** whereas NumPy uses the CPU.

### Practice

In [22]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
l = torch.tensor(6.)
m = torch.tensor(7., requires_grad=True)
c = torch.tensor(8.)
d = torch.tensor(9., requires_grad=True)
y = w * x + b
z = l * y + m
w = c * z + d
y.backward()

In [23]:
print(x.grad, w.grad, b.grad)

None None tensor(1.)


In [24]:
w

tensor(881., grad_fn=<AddBackward0>)

In [25]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = torch.tensor([
    [
        [w * b, b + x],
        [x - b, x * w]
    ],
    [
        [x + w, b * x],
        [x - w, b - w]
    ]
], requires_grad=True)

In [26]:
y[0][0][0].backward()

In [27]:
w.grad, b.grad

(None, None)

In [28]:
x = torch.tensor([
    [1., 2.],
    [3., 4.],
    [5., 6.]
])
w = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
], requires_grad=True)
b = torch.tensor(7., requires_grad=True)
y = x * w.t() + b

In [29]:
y[0][0].backward()

In [30]:
x.grad, w.grad, b.grad

(None,
 tensor([[1., 0., 0.],
         [0., 0., 0.]]),
 tensor(1.))

**Note:** Never iterate over tensors. Always, try to find tensor operation as it will be faster to process than vanilla python loops