# NumPy Indexing and Selection

In [1]:
import numpy as np

## 1D Array

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:6]

array([1, 2, 3, 4, 5])

### Broadcasting

In [6]:
arr[1:6] = 100

In [7]:
arr

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0, 11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

__Note: When a slice is asigned to variable, data is not copied but is just a view of original array. This is done to preserve memory.__

In [10]:
slice_arr = arr[5:9]

In [11]:
slice_arr

array([5, 6, 7, 8])

In [12]:
slice_arr[:] = 99

In [13]:
slice_arr

array([99, 99, 99, 99])

In [14]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99,  9, 10])

__If you specifically require a copy of original array, use copy() method__

In [15]:
arr = np.arange(0, 11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_cp = arr.copy()

In [18]:
arr_cp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_cp[:] = 100

In [20]:
arr_cp

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Array (Matrix)

In [22]:
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1][1]

25

In [26]:
arr_2d[1, 1]

25

In [27]:
arr_2d[1, ]

array([20, 25, 30])

In [30]:
arr_2d[1, 0:2]

array([20, 25])

In [31]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[:, 1]

array([10, 25, 40])

## Conditional Selection

In [34]:
arr = np.arange(1, 11)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [39]:
bool_arr = arr < 4

In [40]:
bool_arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [41]:
arr[bool_arr]

array([1, 2, 3])

In [42]:
arr[arr > 8]

array([ 9, 10])

In [43]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [44]:
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [45]:
arr_2d = np.arange(50).reshape(5, 10)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
arr_2d[arr_2d % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])