# NumPy Arrays

In [4]:
import numpy as np

In [5]:
lst = [1, 2, 3, 4, 5]

In [6]:
np.array(lst)

array([1, 2, 3, 4, 5])

#### np.arange() is similar to range() function

In [7]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

#### To get array of zeros 

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### To get array of ones

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### np.linspace(start, end, num) will provide 'num' diffrent points between 'start' (inclusive) and 'end' (inclusive) that are equidistant to each other

In [13]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

#### Identity Matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random Number Generation

#### Uniform Distribution from 0 to 1

In [16]:
np.random.rand(50)

array([0.76506859, 0.11225025, 0.28220021, 0.11120619, 0.73069876,
       0.36717451, 0.58306904, 0.02855466, 0.83610094, 0.5393323 ,
       0.52347888, 0.14923177, 0.3980827 , 0.52627402, 0.74281526,
       0.90091803, 0.90529365, 0.84034235, 0.34465605, 0.71101055,
       0.33678615, 0.447826  , 0.56708739, 0.96985838, 0.67483254,
       0.56590588, 0.66539189, 0.77824647, 0.29658501, 0.67024958,
       0.1363188 , 0.20797635, 0.91288983, 0.29780245, 0.69614219,
       0.25148275, 0.04438167, 0.09037472, 0.47495624, 0.31795663,
       0.92629663, 0.78921467, 0.38191162, 0.32410584, 0.10840483,
       0.70653138, 0.78798981, 0.009504  , 0.96119281, 0.66741323])

In [17]:
np.random.rand(3, 20)

array([[0.71775266, 0.17476693, 0.84655279, 0.54476051, 0.70970892,
        0.85314532, 0.6312294 , 0.97249875, 0.36398704, 0.56949821,
        0.05658857, 0.53542058, 0.01728199, 0.6009337 , 0.14346202,
        0.08531981, 0.32518607, 0.73198278, 0.5389915 , 0.99720066],
       [0.28644898, 0.48566139, 0.686888  , 0.49300227, 0.45660063,
        0.2728566 , 0.99177917, 0.7477029 , 0.20149303, 0.9815143 ,
        0.73653646, 0.07133163, 0.72241128, 0.9783131 , 0.54537886,
        0.79645522, 0.47388828, 0.24667648, 0.27659302, 0.37444263],
       [0.54619695, 0.94283325, 0.43394779, 0.21450463, 0.24224386,
        0.77680113, 0.05319549, 0.78784649, 0.07478648, 0.09241598,
        0.64115528, 0.77751501, 0.59702374, 0.72838927, 0.36353314,
        0.14442324, 0.82726093, 0.3227685 , 0.20002855, 0.55148065]])

#### Normal / Gaussian Distribution centered around 0

In [18]:
np.random.randn(30)

array([-0.66592335,  0.48266334,  0.91128308,  0.1723612 , -1.276979  ,
       -0.09320136,  0.49254852,  1.12916785, -1.92650882,  1.2105855 ,
        1.87904134, -0.1586826 ,  0.14044737, -0.05021228, -0.2090706 ,
       -0.20698828, -0.81870736,  1.32239744,  1.40439434,  0.34670705,
       -0.569087  , -0.0092978 , -1.02008813,  1.21844049, -0.15405695,
        0.84988245, -1.86769681, -0.47450731, -2.39633743,  1.28975408])

In [19]:
np.random.randn(2, 12)

array([[-0.16020248, -0.2468485 , -1.04844251,  0.26456787, -1.52844331,
         0.57858506,  0.55821025,  0.64903579, -0.17882859,  1.31268599,
        -0.57310315,  0.30712239],
       [ 0.12581774, -0.52445486, -0.09262364, -0.85141641, -0.55648191,
        -0.69730106,  1.26116174,  0.23670912, -0.41879954,  1.06511535,
         0.29165596, -1.5009589 ]])

#### Random integers from 'low' (inclusive) to 'high' (exclusive)

In [20]:
np.random.randint(1, 100)

50

In [22]:
np.random.randint(1, 100, 25)

array([34, 78, 32, 50, 27, 75, 55, 53, 24, 55, 59, 18, 30, 54, 13, 65, 22,
       99, 17,  4, 49, 71, 17, 69, 54])

### Attributes and Methods for NP Arrays

In [23]:
arr = np.arange(0, 20)
ranarr = np.random.randint(0, 50, 10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
ranarr

array([ 1, 16, 49,  6, 25, 12, 17, 14, 23, 24])

#### Reshape dimentionality of the array

In [27]:
arr.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
arr.reshape(5, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

#### Max and Min

In [29]:
ranarr.max()

49

In [30]:
ranarr.min()

1

In [32]:
ranarr.argmax()

2

In [33]:
ranarr.argmin()

0

#### Shape

In [34]:
arr.shape

(20,)

In [37]:
rearr = arr.reshape(5, 4)

In [38]:
rearr.shape

(5, 4)

#### Data Type

In [39]:
arr.dtype

dtype('int64')